=== Facebook-Governance/AutomationFramework/APITestSuite/target/test-classes/TestData/CSVFiles/Insights/CustomerSubscriptionSchema/INVESTMENT_MATURITY_NOTICE.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "insightName": {
      "type": "string"
    },
    "insightTitle": {
      "type": "string"
    },
    "insightType": {
      "type": "string"
    },
    "triggerType": {
      "type": "string"
    },
    "container": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "description": {
      "type": "string"
    },
    "applicableEntity": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "customerConfiguration": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "entityType": {
              "type": "string"
            },
            "isSubscribed": {
              "type": "boolean"
            },
            "frequency": {
              "type": "string"
            },
            "threshold": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "value",
                    "type"
                  ]
                }
              ]
            }
          },
          "required": [
            "entityType",
            "isSubscribed",
            "frequency",
            "threshold"
          ]
        }
      ]
    }
  },
  "required": [
    "insightName",
    "insightTitle",
    "insightType",
    "triggerType",
    "container",
    "description",
    "applicableEntity",
    "customerConfiguration"
  ]
}

=== Facebook-Governance/AutomationFramework/APITestSuite/target/test-classes/TestData/CSVFiles/Insights/CustomerSubscriptionSchema/SPENDING_EXCEEDED_AVERAGE.json
{
            "insightName": "SPENDING_EXCEEDED_AVERAGE",
            "insightTitle": "Spending Exceeded Average",
            "insightType": "OTHER",
            "triggerType": "REFRESH",
            "container": [
                "BANK",
                "CARD"
            ],
            "description": "Generates an insight when the difference, per category, between current spending and average spending over the previous three months is more than a configured threshold.",
            "applicableEntity": [
                "ACCOUNT"
            ],
            "customerConfiguration": [
                {
                    "entityType": "ACCOUNT",
                    "isSubscribed": false,
                    "threshold": [
                        {
                            "name": "CHANGE",
                            "value": "50.00",
                            "type": "AMOUNT"
                        },
                        {
                            "name": "CHANGE",
                            "value": "10.00",
                            "type": "PERCENT"
                        }
                    ]
                }
            ]
        }
