=== Facebook-Governance/AutomationFramework/APITestSuite/src/test/resources/TestData/CSVFiles/Insights/UserSubscriptionSchema/COUNT_OF_TRANSACTIONS_BY_MERCHANT.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "insightName": {
      "type": "string"
    },
    "insightTitle": {
      "type": "string"
    },
    "insightType": {
      "type": "string"
    },
    "triggerType": {
      "type": "string"
    },
    "container": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "description": {
      "type": "string"
    },
    "applicableEntity": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "userConfiguration": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "entityType": {
              "type": "string"
            },
            "isSubscribed": {
              "type": "boolean"
            },
            "frequency": {
              "type": "string"
            },
            "duration": {
              "type": "string"
            },
            "threshold": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "value",
                    "type"
                  ]
                }
              ]
            }
          },
          "required": [
            "entityType",
            "isSubscribed",
            "frequency",
            "duration",
            "threshold"
          ]
        },
        {
          "type": "object",
          "properties": {
            "entityType": {
              "type": "string"
            },
            "isSubscribed": {
              "type": "boolean"
            },
            "frequency": {
              "type": "string"
            },
            "duration": {
              "type": "string"
            },
            "threshold": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "value",
                    "type"
                  ]
                }
              ]
            }
          },
          "required": [
            "entityType",
            "isSubscribed",
            "frequency",
            "duration",
            "threshold"
          ]
        }
      ]
    },
    "customerConfiguration": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "entityType": {
              "type": "string"
            },
            "isSubscribed": {
              "type": "boolean"
            },
            "frequency": {
              "type": "string"
            },
            "duration": {
              "type": "string"
            },
            "threshold": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "value",
                    "type"
                  ]
                }
              ]
            }
          },
          "required": [
            "entityType",
            "isSubscribed",
            "frequency",
            "duration",
            "threshold"
          ]
        },
        {
          "type": "object",
          "properties": {
            "entityType": {
              "type": "string"
            },
            "isSubscribed": {
              "type": "boolean"
            },
            "frequency": {
              "type": "string"
            },
            "duration": {
              "type": "string"
            },
            "threshold": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "value",
                    "type"
                  ]
                }
              ]
            }
          },
          "required": [
            "entityType",
            "isSubscribed",
            "frequency",
            "duration",
            "threshold"
          ]
        }
      ]
    }
  },
  "required": [
    "insightName",
    "insightTitle",
    "insightType",
    "triggerType",
    "container",
    "description",
    "applicableEntity",
    "userConfiguration",
    "customerConfiguration"
  ]
}

=== Facebook-Governance/AutomationFramework/APITestSuite/target/test-classes/TestData/CSVFiles/Insights/UserSubscriptionSchema/CREDIT_UTILIZATION_SINGLE_CARD.json
{
            "insightName": "CREDIT_UTILIZATION_ALL_CARDS",
            "insightTitle": "Credit Utilization Warning (all cards)",
            "insightType": "AGGREGATE",
            "triggerType": "REFRESH",
            "container": [
                "CARD"
            ],
            "description": "Generates an insight when the balance on all credit cards is more than a configured threshold.",
            "applicableEntity": [
                "ACCOUNT"
            ],
            "userConfiguration": [
                {
                    "entityType": "ACCOUNT",
                    "isSubscribed": true,
                    "threshold": [
                        {
                            "name": "UPPER_LIMIT",
                            "value": "30",
                            "type": "PERCENT"
                        }
                    ]
                }
            ],
            "customerConfiguration": [
                {
                    "entityType": "ACCOUNT",
                    "isSubscribed": true,
                    "threshold": [
                        {
                            "name": "UPPER_LIMIT",
                            "value": "30",
                            "type": "PERCENT"
                        }
                    ]
                }
            ]
        }
